replicaCount: 2
image:
  repository: medcrm/billing-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  enabled: true
  port: 3009
  tcpPort: 3010

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

pdb:
  enabled: true
  minAvailable: 1

networkPolicy:
  enabled: true
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: api-gateway
      ports:
        - protocol: TCP
          port: 3009
        - protocol: TCP
          port: 3010

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi

env: {}
