const tables = [
  'appointment_notifications',
  'appointment_recurrence_rules',
  'appointment_reservations',
  'appointment_resources',
  'appointment_status_history',
  'appointment_visit_states',
  'appointments',
  'audit_logs',
  'availability_caches',
  'branches',
  'call_events',
  'cashier_shifts',
  'chatbot_actions_log',
  'chatbot_flows',
  'clinical_compositions',
  'clinical_elements',
  'clinical_observations',
  'clinical_sections',
  'clinical_templates',
  'communication_campaigns',
  'communication_channels',
  'communication_metrics',
  'communication_preferences',
  'conversation_assignments',
  'conversation_participants',
  'conversations',
  'crm_tags',
  'departments',
  'device_measurements',
  'digital_signatures',
  'doctor_kpi_metrics',
  'dw_fact_appointments',
  'dw_fact_marketing',
  'dw_fact_payments',
  'employee_positions',
  'employee_room_assignments',
  'employees',
  'encounter_diagnoses',
  'encounter_versions',
  'encounters',
  'episodes_of_care',
  'equipment',
  'equipment_categories',
  'family_groups',
  'family_members',
  'family_wallets',
  'file_links',
  'files',
  'financial_daily_aggregates',
  'gateway_transactions',
  'generated_reports',
  'incoming_calls',
  'integration_logs',
  'integration_metrics',
  'integration_providers',
  'inventory_audits',
  'inventory_balances',
  'inventory_batches',
  'inventory_categories',
  'inventory_consumptions',
  'inventory_items',
  'inventory_transactions',
  'inventory_transfers',
  'invoice_items',
  'invoices',
  'lab_orders',
  'lab_results',
  'laboratory_providers',
  'legal_document_templates',
  'legal_document_types',
  'marketing_funnel_metrics',
  'medical_devices',
  'medical_files',
  'medical_records',
  'message_attachments',
  'message_templates',
  'messages',
  'no_show_metrics',
  'notification_rules',
  'notifications_queue',
  'online_booking_tokens',
  'patient_addresses',
  'patient_contacts',
  'patient_crm_metrics',
  'patient_debts',
  'patient_leads',
  'patient_legal_documents',
  'patient_notes',
  'patient_tags',
  'patient_timeline_events',
  'patient_wallets',
  'patients',
  'payment_allocations',
  'payment_gateways',
  'payments',
  'payroll_calculations',
  'payroll_rules',
  'positions',
  'prescription_items',
  'prescriptions',
  'procedure_orders',
  'purchase_orders',
  'realtime_metrics_cache',
  'receptionist_dashboards_cache',
  'refunds',
  'resource_buffers',
  'retention_metrics',
  'roles',
  'room_types',
  'room_utilization_metrics',
  'rooms',
  'schedule_exceptions',
  'scheduled_reports',
  'service_bom_templates',
  'service_required_resources',
  'services',
  'sms_providers',
  'stock_alert_rules',
  'stock_alerts',
  'storage_providers',
  'suppliers',
  'telephony_providers',
  'tenant_modules',
  'tenant_subscriptions',
  'tenant_usage_metrics',
  'user_branch_roles',
  'user_sessions',
  'users',
  'visit_queue',
  'waiting_lists',
  'wallet_transactions',
  'warehouses',
  'webhook_events',
  'working_schedules',
  // Added from new schema tables
  'encryption_keys',
];

function generate() {
  let sql = `-- Migration: Enable RLS on tenant-scoped tables\n\n`;
  sql += `-- 1) Helper functions to get session context variables\n`;
  sql += `CREATE OR REPLACE FUNCTION current_tenant_id() RETURNS uuid AS $$\n`;
  sql += `  SELECT NULLIF(current_setting('app.current_tenant_id', true), '')::uuid;\n`;
  sql += `$$ LANGUAGE sql STABLE;\n\n`;

  sql += `CREATE OR REPLACE FUNCTION current_user_id() RETURNS uuid AS $$\n`;
  sql += `  SELECT NULLIF(current_setting('app.current_user_id', true), '')::uuid;\n`;
  sql += `$$ LANGUAGE sql STABLE;\n\n`;

  sql += `-- 2) Enable RLS and create isolation policy for each table\n`;
  for (const table of tables.sort()) {
    sql += `-- Table: ${table}\n`;
    sql += `ALTER TABLE "${table}" ENABLE ROW LEVEL SECURITY;\n`;
    sql += `ALTER TABLE "${table}" FORCE ROW LEVEL SECURITY;\n`;
    sql += `DROP POLICY IF EXISTS "${table}_tenant_isolation" ON "${table}";\n`;
    sql += `CREATE POLICY "${table}_tenant_isolation" ON "${table}"\n`;
    sql += `  USING (tenant_id = current_tenant_id())\n`;
    sql += `  WITH CHECK (tenant_id = current_tenant_id());\n\n`;
  }

  console.log(sql);
}

generate();
